CREATE TABLE boking (
    id INT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    date VARCHAR(100) NOT NULL,
    timestart VARCHAR(100) NOT NULL,
    timeend VARCHAR(100) NOT NULL,
    Type VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    anyting VARCHAR(1000) NOT NULL,
    Image VARCHAR(100) NOT NULL,
    status VARCHAR(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;